site:
  title: Embassy Docs
  url: https://embassy.dev/book
  start_page: ROOT::index.adoc

content:
  sources:
    - url: https://github.com/embassy-rs/embassy.git
      branches: master
      start_path: docs
ui: 
  bundle:
    url: https://github.com/embassy-rs/embassy-antora-ui/releases/download/0.2.2/ui-bundle.zip
    snapshot: true

output:
  clean: true
runtime:
  fetch: true

